# H2 Properties
spring:

  application:
    name: E-Commerce-Portal
  
server:
  port: 8000
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://3.142.148.8:8761/eureka